### ISSUE TITLE
Unix style insertion arguments are expanded, long style aren't

### ISSUE THREAD

**Issue by bergsalex** [jacobsalmela/tccutil#14]
This is really strange to me and I'm not quite sure what to make of it. I looked through the code and can't tell where this is happening or why, hence I post a mystery rather than a solution.

I'm running OSx 10.11.4 and trying to add /usr/bin/python to my accessibility settings. I've got several versions of python on my computer and several even in /usr/bin/. Here's an example of the expansion that goes on:

```
$ which python
/usr/bin/python
$ sudo tccutil -i /usr/bin/python -v
Opening Database...
Database opened.

Detected "/usr/bin/python2.7" as Command Line Utility.
Inserting "/usr/bin/python2.7" into Database...
Committing Changes...

Closing Database...
Database closed.
```

However, if I use long style arguments it seems to work fine:

```
$ sudo tccutil --insert="/usr/bin/python" -v
Opening Database...
Database opened.

Detected "/usr/bin/python" as Command Line Utility.
Inserting "/usr/bin/python" into Database...
Committing Changes...

Closing Database...
Database closed.
```

Hope this is enough to track down the problem. I might have another stab at it tomorrow with some fresh perspective.

**Comment by jacobsalmela** [comment]
@bergsalex Can you try this again?  `argparse` is now used and I'm just wondering if it fixes the issue?

**Comment by jacobsalmela** [comment]
@bergsalex I'm going to close this unless you state otherwise.
