### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by MoOx** [jacobsalmela/tccutil#2]
I just downloaded your utility as a submodule & when I try to list existing entry I'm getting this issue.

```console
$ pwd
/Users/MoOx/setup

$ ./submodules/tccutil/tccutil.py --list
Traceback (most recent call last):
  File "/Users/MoOx/setup/submodules/tccutil/tccutil.py", line 16, in <module>
    conn = sqlite3.connect(tcc_db)
sqlite3.OperationalError: unable to open database file
```

**Comment by MoOx** [comment]
Running with sudo seems to fix the problem. Should be added to doc?

**Comment by jacobsalmela** [comment]
I'm glad you figured out that sudo was necessary.  Where do you think is
the best spot to mention this?  On the github repo README, I show the
commands being used with sudo.  Maybe you can make me an issue on the repo
and I will resolve it by saying sudo needs to be used.

**Comment by MoOx** [comment]
Indeed it's in the README. So nevermind, user looking for this issue will now find this one :)
Thanks for your tool!
