### ISSUE TITLE
Validity check on TCC.db fails on macOS 10.11.6

### ISSUE THREAD

**Issue by jpcirrus** [jacobsalmela/tccutil#21]
The merge at f450075 prevents any access to TCC.db on 10.11.6 where I get the error message "TCC Database structure is unknown." I suspect that there is a different `accessTableDigest` hash which is causing this as it runs fine when I comment out lines 112 to 118.

**Comment by mrooney** [comment]
Seeing this as well on 10.11.6. @jacobsalmela, any thoughts on if this is an easy fix?

**Comment by jacobsalmela** [comment]
Sorry about this.  Maybe @antontsv has some insight?

**Comment by jacobsalmela** [comment]
I last tested it on 10.11.4, so maybe something changed slightly in 10.11.6?

**Comment by jpcirrus** [comment]
I have upgraded to Sierra 10.12.1 and am getting the same error.

**Comment by antontsv** [comment]
Someone at Apple is has decided to give table names nice quoted form. Table structure has not changed. Here is a new hash:
https://github.com/jacobsalmela/tccutil/pull/22

For MacOS Sierra I have just compared file structure. I am personally running OS with SIP on.

**Comment by jpcirrus** [comment]
@antontsv thanks for that. I confirm that #22 fixes it on SIP disabled 10.12.1.

**Comment by jacobsalmela** [comment]
Solved with #22.  Thanks @antontsv!
