### ISSUE TITLE
How I know service name to insert

### ISSUE THREAD

**Issue by congdv** [jacobsalmela/tccutil#23]
Hi,
I have a question that how I know service name of my application for insert to database. 
Example: I want to Eclipse IDE could be Accessibility  but I really don't know name of Eclipse IDE.
I tried "sudo tccutil.py --insert /Applications/Eclipse.app" but it 's not working.
Like "ScriptEditor2" is "com.apple.ScriptEditor2".
Thank you.

**Comment by jacobsalmela** [comment]
Sorry I missed this one @congdv:

It's the _Bundle ID_ you are looking for.  I typically use a command like this to find it:

```
/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/Eclipse.app/Contents/Info.plist
```
