### ISSUE TITLE
db is read only?

### ISSUE THREAD

**Issue by fallenreaper** [jacobsalmela/tccutil#24]
c.execute("INSERT or REPLACE INTO access VALUES('kTCCServiceAccessibility','%s',%s,1,1,NULL,NULL)" % (client, client_type))
sqlite3.OperationalError: attempt to write a readonly database

not sure why it is read only.

**Comment by myadhdoutlet** [comment]
The file is now protected by Apple's SIP, so yes, it's effectively read-only unless you disable SIP.

**Comment by jacobsalmela** [comment]
Yep.  I currently have no plans to try to circumvent Apple's SIP.  But I think my utility would make a great addition to their arsenal...

**For now, the workaround is to disable SIP.**
