### ISSUE TITLE
failed to reset CoreLocationAgent 

### ISSUE THREAD

**Issue by singular78** [jacobsalmela/tccutil#26]
`> tccutil reset CoreLocationAgent` 
`> failed to reset database`

The macOS version is 10.13.1.
Is the location database stored in tcc.db on this version of macOS ?

**Comment by jacobsalmela** [comment]
I do not believe `CoreLocation` is part of the TCC database.  Look here: `/var/db/locationd/clients.plist`

**Comment by singular78** [comment]
Thank you!
