### ISSUE TITLE
TCC Database structure is unknown (macOS 10.14)

### ISSUE THREAD

**Issue by w0lfschild** [jacobsalmela/tccutil#27]
Some changes have been made in Mojave. Running the script results in this error:

```
TCC Database structure is unknown.
Error opening Database.
```

**Comment by Kwask94** [comment]
Same Problem here

**Comment by syammala** [comment]
tccutil --list
TCC Database structure is unknown.
Error opening Database.  tccutil is always returning error with 10.14.1. Even tccutil reset AppleEvents is not working. Any update ?

**Comment by MHolmes91** [comment]
PR  #28 should address this issue.

**Comment by jacobsalmela** [comment]
#28 was merged

**Comment by Mirone** [comment]
Same problem Here Catalina 10.15 (19A602).

**Comment by jacobsalmela** [comment]
With the merge above?

**Comment by Mirone** [comment]
> With the merge above?

Yes.

**Comment by timepigeon** [comment]
Still getting the same error with version 1.2.3 from homebrew using macos 10.14. Is there a way to get more debug output to resolve this?

**Comment by jacobsalmela** [comment]
I haven't updated that homebrew version for some time.  Try cloning this repo and installing that way.

**Comment by LucasVanDongen** [comment]
Getting just the database error:

```
mine@Mines-MBP tccutil % sudo python tccutil.py -i /usr/bin/osascript
Password:
Error opening Database.
```

**Comment by jacobsalmela** [comment]
Yep.  You need to have SIP disabled.  I meant to add a message to show that
