### ISSUE TITLE
Installing Safari Extension Question

### ISSUE THREAD

**Issue by dhoer** [jacobsalmela/tccutil#3]
I'm trying to get a script to install Safari Extensions: 

Should the following work or am I missing a step?  I keep getting:
`246:261: execution error: System Events got an error: osascript is not allowed assistive access. (-25211)`

```
sudo tccutil.py -i /usr/bin/osascript
sudo tccutil.py -e /usr/bin/osascript

osascript -e 'tell application "Safari"
  activate
end tell'

osascript -e 'ignoring application responses
  tell application "Safari"
    open "'"/tmp/SafariDriver.safariextz"'"
    end tell
end ignoring
tell application "System Events"
  tell process "Safari"
    set frontmost to true
      repeat until (exists window 1) and subrole of window 1 is "AXDialog" -- wait until the dialog is displayed.
        delay 1
      end repeat
    click button 1 of front window -- install
  end tell
end tell'

**Comment by jacobsalmela** [comment]
Despite its name, you need to [dd ARDAgent.app to the accessibility database](http://jacobsalmela.com/bash-script-enable-access-assistive-devices-programmatically-os-x-mavericks-10-9-x-simulate-keystrokes/#osascript)a using this command.

`sudo tccutil.py -i com.apple.RemoteDesktopAgent`

**Comment by dhoer** [comment]
Thanks for your help and taking the time to create and blog about your approach.  I would have not been able to get safari configured to support selenium without it.  I should have a chef safari cookbook built on top of your script sometime this week: https://github.com/dhoer/chef-safari/blob/master/test/fixtures/cookbooks/safari_test/recipes/extension.rb

**Comment by jacobsalmela** [comment]
Cool.  No problem.
