### ISSUE TITLE
  File "./tccutil", line 76     print "%s %s" % (util_name, util_version)

### ISSUE THREAD

**Issue by apwelsh** [jacobsalmela/tccutil#30]
On MacOS Catalina, where the default python is python3, it reports

  File "./tccutil", line 76
    print "%s %s" % (util_name, util_version)

Consider either updating code to python3, or declare the version in the first line, as "python2"

**Comment by jacobsalmela** [comment]
I should do some updates to this product...people still use it on new systems like Catalina?  I kind of abandoned work on after SIP was introduced, but if people still find it useful, I can do some updates to it.

**Comment by jacobsalmela** [comment]
Yeah, those bundle IDs are useful to find...maybe it just needs a small tweak to say it works before version x and it's still useful for older versions of macOS to adjust things...

**Comment by apwelsh** [comment]
Don’t know because it doesn’t work as-is. Curious why rootless would be an issue. I installed from brew which puts the files in /use/local/... to avoid system integrity protections. 
I have not looked at the source code to see what you do, but so long as you use system services you can still change system configurations with proper authorization.
