### ISSUE TITLE
El Capitan needs a 7th NULL parameter when inserting.

### ISSUE THREAD

**Issue by reitermarkus** [jacobsalmela/tccutil#4]
I just discovered this awesome utility and on El Capitan it seems you have to pass a 7th parameter with `NULL`, otherwise it throws an error.

**Comment by jacobsalmela** [comment]
Interesting.  I'll have to look into this.  Thanks!

**Comment by MoOx** [comment]
Just discover the same issue.

**Comment by tjluoma** [comment]
Ditto :-)
