### ISSUE TITLE
Question: what parts of SIP need to be disabled?

### ISSUE THREAD

**Issue by knowler** [jacobsalmela/tccutil#40]
Does SIP need to be completely disabled or can one get away with disabling parts of it? I am using the following configuration, but I still get the SIP error from this tool.

```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

This is on macOS 11.0.1 Big Sur.

**Comment by jacobsalmela** [comment]
I haven't done anything on Big Sur yet.  From what you posted, I'd guess Filesystem Protections and BaseSystem Verifcation

**Comment by jacobsalmela** [comment]
I'm moving this into a Discussion.

#44

**Comment by sclsj** [comment]
Only the Filesystem Protections. You also need to add Terminal to "Whole Disk Access".
