### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by dhoer** [jacobsalmela/tccutil#5]
I was wondering if it would be possible to add support for the following:

1) Create database if not there.  An example can be found here: https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/blob/master/privacy_services_management/tcc_services.py#L349

2) Support Contacts, Calendars, iCloud and Reminders.  An example of how this could be done is here: https://github.com/univ-of-utah-marriott-library-apple/privacy_services_manager/blob/master/privacy_services_management/tcc_services.py#L15-L19

**Comment by jacobsalmela** [comment]
I have been wanting to do this for a long time.  I was actually talking with those people about collaborating.  I won't have much time for it right now as I'm focusing on the Pi-hole while still trying to work my regular job.  Maybe someone in the community can help out with a PR...

**Comment by dhoer** [comment]
No problem. I thought about a hybrid script that
uses privacy-security-manager  to create db and your clean simple way of
updating it.  But I don't know python and have other priorities.  It looks
like El Capitan will require more changes than just adding a column
according to privacy-security-manager folks.

In the mean time, I call their script to create the database and yours to
update it.

**Comment by dhoer** [comment]
The privacy-security-manager script now support El Capitan and they fixed some of the issues I had.  So I'm closing this request. Thanks
