### ISSUE TITLE
--Enable  with ScreenCapture or Accessability flags returns no error, but does not change setting 

### ISSUE THREAD

**Issue by Brink2Three** [jacobsalmela/tccutil#52]
I'm attempting to use this to allow an RMM agent to have ScreenCapture, Accessability (for remote input) and Full disk access via TCCUtil. 

I tried a generic `sudo tccutil -e com.RMMAgent.tray`, but nothing changes in system preferences, and the agent still does not have access to these functions. 

I've tried a meld of the old version of TCCutil with `sudo tccutil -e ScreenCapture com.RMMAgent.tray` 
(as referenced here: https://apple.stackexchange.com/questions/384230/how-do-i-reset-screen-recording-permission-on-macos-catalina)
But that doesn't appear to work. 
Is this a possible function that I am using incorrectly?

Info: 
MacBookAir8,1
i5, 8GB
MacOS 11.4 20F71
Kernel Darwin 20.5.0
System Integrity Protection: Disabled

**Comment by jacobsalmela** [comment]
@Brink2Three did you do a `tccutil -i` first?

**Comment by fharper** [comment]
I was wondering why I didn't get an error while trying to add ScreenCapture also. Looking forward for this feature also :)

**Comment by jacobsalmela** [comment]
I'm not going to add the capability to add to screen capture, camera, and/or microphone sections.
