### ISSUE TITLE
command not found: tccutil.py

### ISSUE THREAD

**Issue by gcpmusic** [jacobsalmela/tccutil#56]
I have update to Monterey 12.3 (Intel) and installed via brew install tccutil but I get this:
<img width="366" alt="Screenshot 2022-03-20 at 14 40 45" src="https://user-images.githubusercontent.com/32528176/159165295-7bb35c2b-5d61-4003-84d9-80ba310584cb.png">

Any suggestion please?
Thanks

**Comment by Joshfindit** [comment]
Brew actually installs it as `tccutil`.
`tccutil.py` seems to be an outdated filename

**Comment by jacobsalmela** [comment]
Correct.  You can call `tccutil.py` if you clone the repo and run it locally.  

Otherwise it simply installs as `tccutil` and may be prioritized first depending on your `PATH`
