### ISSUE TITLE
Homebrew package?

### ISSUE THREAD

**Issue by danielbayley** [jacobsalmela/tccutil#7]
It would be handy if we could get this as a [Homebrew](http://brew.sh) package.

**Comment by jacobsalmela** [comment]
I'm not quite sure how to achieve this, but I can look into it.

**Comment by reitermarkus** [comment]
I think Homebrew has a “popularity” requirement for packages hosted on GitHub to be included in the main repo.

>10 watchers, >10 forks and >20 stars

So only 2 more forks are needed.

**Comment by danielbayley** [comment]
> I think Homebrew has a “popularity” requirement for packages hosted on GitHub to be included in the main repo.

    >=10 watchers, >=10 forks, >=20 stars

I wasn't aware the threshold was that low actually. Well I just forked so that's another. I think you can also create a `brew tap` formula for more obscure packages.

**Comment by reitermarkus** [comment]
Yeah, I also thought it was higher, like 50+ Stars or something like that. But I then I looked at an old pull request https://github.com/Homebrew/homebrew/pull/41188#issuecomment-120637294.

**Comment by jacobsalmela** [comment]
If it were to get in Homebrew, then I would probably put some more effort into this so eventually, the tool could be used for editing all of the Security & Privacy settings.  I believe the Location Services, Contacts, Calendars, etc. are also part of the same database.

**Comment by reitermarkus** [comment]
I created a formula and put it in my personal tap for now, you try it using:

    brew install reitermarkus/tap/tccutil --HEAD

When there are enough forks I'll submit it to the main repo. @jacobsalmela, you could create another release so it can be installed without using `--HEAD`.

**Comment by jacobsalmela** [comment]
Awesome.  Thanks!!

**Comment by jacobsalmela** [comment]
It looks like the criteria is met.  How do I make it available via homebrew?

**Comment by danielbayley** [comment]
See the [Formula Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md).

**Comment by reitermarkus** [comment]
I'll change the formula in my tap and submit it to the main repo.

**Comment by reitermarkus** [comment]
https://github.com/Homebrew/homebrew/pull/46718

**Comment by reitermarkus** [comment]
Ok, it's now available in the main Homebrew repo.

    brew install tccutil

**Comment by danielbayley** [comment]
:+1:

**Comment by jacobsalmela** [comment]
Whoa awesome!  Thanks!
